### PR TITLE
Update xgb.py

### PR DESCRIPTION
**Pull request by AdityaSoni19031997**
i should be incremented (typo)

Works thereafter as expected..
```
[mlcrate] Overall feature importances: [('trainee_id', 23564), ('age', 11379), ('test_id', 8937), ('total_programs_enrolled', 3853), ('col_8', 3788), ('col_2', 3637), ('city_tier', 3327), ('col_9', 3012), ('col_1', 2965), ('col_5', 2783), ('col_6', 2542), ('col_4', 2314), ('col_0', 2161), ('program_duration', 2151), ('col_3', 1814), ('col_7', 1454), ('is_age_39_45', 590), ('is_age_39', 138), ('is_age_45', 126)]
```

### CODE REVIEW

**Comment by mxbi** [comment]
Thanks, glad you could sort this one out.

I'm a little confused why incrementing i manually helps here though - because i is generated in the `enumerate()` call, it is already incremented by one every loop. The `i += 1` should have no effect as there is no code run after it before i is overwritten again.

I'm happy to merge because it can't hurt, but I'm curious if you have an example which fails on the old code but works here (so I can try and figure out where the problem actually comes from).

**Comment by AdityaSoni19031997** [comment]
Hey there, I have re-generated the error...

**Comment by mxbi** [comment]
@AdityaSoni19031997 Thanks, I got the files - looking at the csvs I don't see anything out of place. Could you provide your script that produces this traceback?

**Comment by AdityaSoni19031997** [comment]
@mxbi  I ain't sure whether this happens with you or not, but the feat imp part also reports a traceback if You are passing a np.hstack() array as the parameters...

Returning with this `np.darray object is not iterable `

**Pull request closed without merging**
